name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build Angular app for production
        run: ng build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages # You can change this if using a different branch
          PUBLISHED_DIR: ./dist # Adjust if using a custom output folder 
